### ISSUE TITLE
Implement the home screen

### ISSUE THREAD

**Issue by PeterVerzijl** [saproto/anke#2]
The home screen should show the user the following things:
- Proto.ink articles
- News articles from the website

**Comment by DennisVinke** [comment]
Proto.Ink articles are retrieved and shown.
News articles are also being retrieved 
Pop-up contains some bugs

Custom Proto.Ink image background grabber did not work out. Will be replaced with library: I.E. Picasso

**Comment by DennisVinke** [comment]
Has been rewritten so this works with Retrofit. 
Adapter needs to be added so the date is converted correctly
