### ISSUE TITLE
Calendar page

### ISSUE THREAD

**Issue by PeterVerzijl** [saproto/anke#5]
The calendar page has four tabs. The first tab shows the most recent calendar events (DONE). The second tab shows the subscribed events. The third tab shows an endlessly scrolling list of all events (this requires the implementation of both way scrolling). The fourth tab shows a calendar view of all events for that particular day.

Finally, a drag to update needs to be implemented alongside a date for the latest update date.

**Comment by DennisVinke** [comment]
Finished, contains one small bug
